[package]
name = "mir_opt"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license="GPL-3.0"

[lib]
doctest = false


[dependencies]
mir = {version = "0.0.0", path = "../mir" }

stdx = {version = "0.0.0", path = "../../lib/stdx" }
workqueue = {version = "0.0.0", path = "../../lib/workqueue" }
bitset = {version = "0.0.0", path = "../../lib/bitset" }

typed-index-collections = "3.0"
ahash = "0.8"
hashbrown = {version = "0.12", features = ["raw"]}
indexmap = "1.6"

[dev-dependencies]
expect-test = "1.1"
mir_reader = {version = "0.0.0", path = "../mir_reader" }
