[package]
name = "verilogae"
version = "0.9.0-beta5"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false
crate-type = ["rlib", "cdylib"]
name = "verilogae"



[dependencies]

syntax = {version = "0.0.0", path = "../syntax"}
basedb = { version = "0.0.0", path = "../basedb" }
hir_def = { version = "0.0.0", path = "../hir_def" }
hir_lower = {version ="0.0.0", path ="../hir_lower"}
hir_ty = { version = "0.0.0", path = "../hir_ty" }

mir = { version = "0.0.0", path = "../mir" }
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }
mir_opt = { version = "0.0.0", path = "../mir_opt" }
mir_autodiff = { version = "0.0.0", path = "../mir_autodiff" }

llvm = { version = "0.0.0", path = "../llvm" }
target = { version = "0.0.0", path = "../target" }
linker = { version = "0.0.0", path = "../linker" }

stdx = { version = "0.0.0", path = "../stdx" }
typed_indexmap = {version = "0.0.0", path = "../typed_indexmap"}
bitset = {version = "0.0.0", path = "../bitset"}
base_n = {version = "1", path = "../../lib/base_n"}
paths = {version = "0.0", path = "../paths"}

lasso = {version = "0.6", features = ["ahash"]}
indexmap = "1.6"
md5 = "0.7"
directories-next = "2"
libloading = "0.7"

rayon-core = "1"

smol_str = "0.1.22"
parking_lot = "0.12"
typed-index-collections = "3"
ahash = "0.7"
arrayvec = "0.7"

anyhow = "1"
termcolor = "1.1"

salsa = "0.17.0-pre.2"

