[package]
name = "hir_ty"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]

# # data-structures = {version = "0.0.0", path = "../data_structures" }
basedb = {version = "0.0.0", path = "../basedb" }
# syntax = {version = "0.0.0", path = "../syntax"}
stdx = {version = "0.0.0", path = "../stdx" }

hir_def = {version = "0.0.0", path = "../hir_def" }
arena = {version = "0.0.0", path = "../arena" }
syntax = {version = "0.0.0", path = "../syntax"}
typed-index-collections = "3.0"

salsa = "0.17.0-pre.2"

text-size = "1.1"

ahash = "0.7"
indexmap = "1.6"
arrayvec = "0.7"
smol_str = {version = "0.1",  default-features = false}

[dev-dependencies]

sourcegen = {version ="0.0.0", path ="../sourcegen"}
parking_lot = "0.12"
expect-test = "1.1"
proc-macro2 = "1.0"
quote = "1.0"
# indexmap = "1.6"
