[package]
name = "vfs"
version = "0.0.0"
description = "TBD"
license="GPL-3.0"
edition = "2021"
rust-version = "1.56"

[lib]
doctest = false

[dependencies]

paths = {path="../../lib/paths",version="0.0.0"}
indexmap = "1.6"
ahash = "0.8"
encoding_rs = "0.8"
chardetng = "0.1"

[package.metadata.cargo-machete]
ignored = ["encoding_rs"]