[package]
name = "openvaf-driver"
version = "23.5.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[[bin]]
name = "openvaf"
path = "src/main.rs"
doctest = false
test = false

[dependencies]

openvaf = { version = "0.1.2", path = "../openvaf" }

clap = "4.3"
directories-next = "2"
path-absolutize = "3.1.0"
anyhow = "1"
termcolor = "1.2"
camino = "1.1.4"
env_logger = "0.10.0"
log = "0.4.19"
backtrace-ext = "0.2.1"
backtrace = "0.3.68"

mimalloc = { version = "*", default-features = false}

[dev-dependencies]
xshell = "0.2.3"
stdx = { version = "0.0.0", path = "../../lib/stdx" }
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }

[[test]]
name = "cli"
harness = false
