[package]
name = "sourcegen"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://gitlab.com/DSPOM/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominently at compact modelling"
license="GPL-3.0"
readme="../README.md"

[lib]
doctest = false

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
xshell = "0.1"
